# ⚠️ Only non-root builds.

[YT-Anddea] # Default patches are applied :
rv-brand = "Anddea"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'Custom branding icon for YouTube' ''Custom header for Youtube'"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding icon for YouTube' -appIcon=xisr_yellow -e 'Custom header for YouTube' -customHeader=yt_premium_wordmark_header_dark.png -e 'Translations for YouTube' -selectedTranslations=fr-rFR -selectedStringResources=fr"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-Anddea] # Default patches are applied :
rv-brand = "Anddea"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
included-patches = "'Custom branding icon for YouTube Music'"
patcher-args = "-e 'Custom branding icon for YouTube Music' -appIcon=xisr_yellow -e 'Translations for YouTube Music' -selectedTranslations=fr-rFR -selectedStringResources=fr"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"

[YT-Morphe] # Default patches are applied, Except line 27 :
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding' -appName=YouTube -appIcon=morphe_adaptive_foreground_custom.png"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-Morphe] # Default patches are applied, but disabled :
enabled = false
rv-brand = "Morphe"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
# apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"

[Spotify] # Default patches are applied, but disabled :
enabled = false
rv-brand = "ReVanced"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
