# ⚠️ Only non-root builds.

[YT] # Default patches are applied, Except line 5 and 6 :
rv-brand = "Morphe"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -OcustomIcon='.github/logos/morphe/'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YT-Revancify] # Default patches are applied, Except line 11 and 12 :
rv-brand = "Blue"
excluded-patches = "'Swipe controls'"
patcher-args = "-e 'Custom branding' -OcustomName=YouTube -OcustomIcon='.github/logos/revancify_blue/'"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music] # Default patches are applied, but disabled :
enabled = false
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"

[Spotify] # Default patches are applied, but disabled :
enabled = false
rv-brand = "ReVanced"
patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
